### ISSUE TITLE
YouTube画像、団体名が長い時にワードラップされない

### ISSUE THREAD

**Issue by TakamiChie** [side-beach-city/SBC.ImageMaker#2]
以下のようなCSSを追加すると良い感じになる。

```css
div#youtube_d {
    width: 344px;
    text-indent: -20px;
    margin-left: 20px;
}
```
